USE [master]
GO

/****** Object:  Database [FileSystem]    Script Date: 2017-08-02 17:32:21 ******/
CREATE DATABASE [FileSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FileSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLSERVER\MSSQL\DATA\FileSystem.mdf' , SIZE = 12288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FileSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLSERVER\MSSQL\DATA\FileSystem_log.ldf' , SIZE = 47616KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FileSystem] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FileSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FileSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FileSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FileSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FileSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FileSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [FileSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FileSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FileSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FileSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FileSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FileSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FileSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FileSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FileSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FileSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FileSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FileSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FileSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FileSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FileSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FileSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FileSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FileSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [FileSystem] SET  MULTI_USER 
GO

ALTER DATABASE [FileSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FileSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FileSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FileSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FileSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FileSystem] SET  READ_WRITE 
GO


